#!/usr/bin/env ruby

require "fileutils"

BASE_DIR = "forked-plugins"

FileUtils.mkdir(BASE_DIR) unless Dir.exist?(BASE_DIR)
Dir.chdir(BASE_DIR)

changed = {
  "dart-vim-plugin" => "https://github.com/dart-lang",
  "greplace.vim" => "https://github.com/vim-scripts",
  "neomake" => "https://github.com/benekastah",
  "rust.vim" => "https://github.com/wting",
  "syntastic" => "https://github.com/scrooloose",
}.map do |repo, upstream|
  `git clone git@github.com:nerdrew/#{repo}.git` unless Dir.exist?(repo)

  Dir.chdir(repo) do
    if /upstream/ !~ `git remote -v`
      `git remote add upstream #{upstream}/#{repo}.git`
      `git fetch upstream`
    end
    `git fresh upstream/master`
    repo if %r{Your branch is up-to-date with 'origin/master'} !~ `git status`
  end
end.compact

exit if changed.empty?

puts "Changed: #{changed.join(', ')}"
