#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"

BASE_DIR = "forked-plugins"

FileUtils.mkdir(BASE_DIR) unless Dir.exist?(BASE_DIR)
Dir.chdir(BASE_DIR)

changed = {
  "dart-vim-plugin" => "https://github.com/dart-lang",
  #"neomake" => "https://github.com/neomake",
  #"syntastic" => "https://github.com/scrooloose",
  "vim-ruby" => "https://github.com/vim-ruby",
  "ale" => "https://github.com/w0rp",
  "rust.vim" => "https://github.com/rust-lang",
  "vim-sh-indent" => "https://github.com/chrisbra",
}.map do |repo, upstream|
  puts repo
  `git clone git@github.com:nerdrew/#{repo}.git` unless Dir.exist?(repo)

  Dir.chdir(repo) do
    unless /upstream/.match?(`git remote -v`)
      `git remote add upstream #{upstream}/#{repo}.git`
      `git fetch upstream`
    end
    `git pull`
    `git fresh upstream/master`
    repo if %r{Your branch is up-to-date with 'origin/master'} !~ `git status`
  end
end.compact

exit if changed.empty?

puts "Changed: #{changed.join(', ')}"
